/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/login": {
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
  };
  "/api/v1/auth/logout": {
    /** Logout */
    post: operations["logout_api_v1_auth_logout_post"];
  };
  "/api/v1/auth/me": {
    /** Me */
    get: operations["me_api_v1_auth_me_get"];
  };
  "/api/v1/auth/change-password": {
    /** Change Password */
    post: operations["change_password_api_v1_auth_change_password_post"];
  };
  "/api/v1/users/": {
    /** List Users */
    get: operations["list_users_api_v1_users__get"];
    /** Create User */
    post: operations["create_user_api_v1_users__post"];
  };
  "/api/v1/users/{username}": {
    /** Update User */
    put: operations["update_user_api_v1_users__username__put"];
    /** Delete User */
    delete: operations["delete_user_api_v1_users__username__delete"];
  };
  "/api/v1/users/{username}/reset-password": {
    /** Reset Password */
    post: operations["reset_password_api_v1_users__username__reset_password_post"];
  };
  "/api/v1/projects/": {
    /** List Projects */
    get: operations["list_projects_api_v1_projects__get"];
    /** Create Project */
    post: operations["create_project_api_v1_projects__post"];
  };
  "/api/v1/projects/{project_id}": {
    /** Get Project */
    get: operations["get_project_api_v1_projects__project_id__get"];
    /** Delete Project */
    delete: operations["delete_project_api_v1_projects__project_id__delete"];
    /** Update Project */
    patch: operations["update_project_api_v1_projects__project_id__patch"];
  };
  "/api/v1/projects/import": {
    /** Import Project */
    post: operations["import_project_api_v1_projects_import_post"];
  };
  "/api/v1/projects/{project_id}/export": {
    /** Export Project */
    get: operations["export_project_api_v1_projects__project_id__export_get"];
  };
  "/api/v1/projects/{project_id}/features": {
    /** List Features */
    get: operations["list_features_api_v1_projects__project_id__features_get"];
    /** Create Feature */
    post: operations["create_feature_api_v1_projects__project_id__features_post"];
    /** Clear All Features */
    delete: operations["clear_all_features_api_v1_projects__project_id__features_delete"];
  };
  "/api/v1/features/{feature_id}": {
    /** Get Feature */
    get: operations["get_feature_api_v1_features__feature_id__get"];
    /** Delete Feature */
    delete: operations["delete_feature_api_v1_features__feature_id__delete"];
    /** Update Feature */
    patch: operations["update_feature_api_v1_features__feature_id__patch"];
  };
  "/api/v1/features/{feature_id}/split": {
    /** Split Feature */
    post: operations["split_feature_api_v1_features__feature_id__split_post"];
  };
  "/api/v1/features/{feature_id}/cancel-continuation": {
    /** Cancel Continuation */
    post: operations["cancel_continuation_api_v1_features__feature_id__cancel_continuation_post"];
  };
  "/api/v1/projects/{project_id}/backlog": {
    /** Clear Backlog */
    delete: operations["clear_backlog_api_v1_projects__project_id__backlog_delete"];
  };
  "/api/v1/projects/{project_id}/pbis": {
    /** List Pbis */
    get: operations["list_pbis_api_v1_projects__project_id__pbis_get"];
    /** Create Pbi */
    post: operations["create_pbi_api_v1_projects__project_id__pbis_post"];
  };
  "/api/v1/pbis/{pbi_id}": {
    /** Get Pbi */
    get: operations["get_pbi_api_v1_pbis__pbi_id__get"];
    /** Delete Pbi */
    delete: operations["delete_pbi_api_v1_pbis__pbi_id__delete"];
    /** Update Pbi */
    patch: operations["update_pbi_api_v1_pbis__pbi_id__patch"];
  };
  "/api/v1/pbis/{pbi_id}/place": {
    /** Place Story In Sprint */
    post: operations["place_story_in_sprint_api_v1_pbis__pbi_id__place_post"];
    /** Unplace Story */
    delete: operations["unplace_story_api_v1_pbis__pbi_id__place_delete"];
  };
  "/api/v1/pis/{pi_id}/events": {
    /** List Events */
    get: operations["list_events_api_v1_pis__pi_id__events_get"];
    /** Create Event */
    post: operations["create_event_api_v1_pis__pi_id__events_post"];
  };
  "/api/v1/pis/{pi_id}/events/{event_id}": {
    /** Delete Event */
    delete: operations["delete_event_api_v1_pis__pi_id__events__event_id__delete"];
    /** Update Event */
    patch: operations["update_event_api_v1_pis__pi_id__events__event_id__patch"];
  };
  "/api/v1/projects/{project_id}/pis": {
    /** List Pis */
    get: operations["list_pis_api_v1_projects__project_id__pis_get"];
    /** Create Pi */
    post: operations["create_pi_api_v1_projects__project_id__pis_post"];
  };
  "/api/v1/pis/{pi_id}": {
    /** Get Pi */
    get: operations["get_pi_api_v1_pis__pi_id__get"];
    /** Delete Pi */
    delete: operations["delete_pi_api_v1_pis__pi_id__delete"];
    /** Update Pi */
    patch: operations["update_pi_api_v1_pis__pi_id__patch"];
  };
  "/api/v1/pis/{pi_id}/export/csv": {
    /** Export Pi Csv Endpoint */
    get: operations["export_pi_csv_endpoint_api_v1_pis__pi_id__export_csv_get"];
  };
  "/api/v1/pis/{pi_id}/export/png": {
    /** Export Pi Png Endpoint */
    get: operations["export_pi_png_endpoint_api_v1_pis__pi_id__export_png_get"];
  };
  "/api/v1/pis/{pi_id}/report": {
    /** Export Pi Report Endpoint */
    get: operations["export_pi_report_endpoint_api_v1_pis__pi_id__report_get"];
  };
  "/api/v1/pis/{pi_id}/export/html": {
    /** Export Pi Dashboard Endpoint */
    get: operations["export_pi_dashboard_endpoint_api_v1_pis__pi_id__export_html_get"];
  };
  "/api/v1/pis/{pi_id}/swimlines": {
    /** List Swimlines */
    get: operations["list_swimlines_api_v1_pis__pi_id__swimlines_get"];
    /** Create Swimline */
    post: operations["create_swimline_api_v1_pis__pi_id__swimlines_post"];
  };
  "/api/v1/swimlines/{swimline_id}": {
    /** Get Swimline */
    get: operations["get_swimline_api_v1_swimlines__swimline_id__get"];
    /** Delete Swimline */
    delete: operations["delete_swimline_api_v1_swimlines__swimline_id__delete"];
    /** Update Swimline */
    patch: operations["update_swimline_api_v1_swimlines__swimline_id__patch"];
  };
  "/api/v1/swimlines/{swimline_id}/reorder": {
    /** Reorder Swimlines */
    post: operations["reorder_swimlines_api_v1_swimlines__swimline_id__reorder_post"];
  };
  "/api/v1/swimlines/{swimline_id}/groups": {
    /** List Groups */
    get: operations["list_groups_api_v1_swimlines__swimline_id__groups_get"];
    /** Create Group */
    post: operations["create_group_api_v1_swimlines__swimline_id__groups_post"];
  };
  "/api/v1/groups/{group_id}": {
    /** Get Group */
    get: operations["get_group_api_v1_groups__group_id__get"];
    /** Delete Group */
    delete: operations["delete_group_api_v1_groups__group_id__delete"];
    /** Update Group */
    patch: operations["update_group_api_v1_groups__group_id__patch"];
  };
  "/api/v1/pis/{pi_id}/sprints": {
    /** List Sprints */
    get: operations["list_sprints_api_v1_pis__pi_id__sprints_get"];
  };
  "/api/v1/sprints/{sprint_id}": {
    /** Update Sprint */
    patch: operations["update_sprint_api_v1_sprints__sprint_id__patch"];
  };
  "/api/v1/projects/{project_id}/edit-lock": {
    /** Get Edit Lock */
    get: operations["get_edit_lock_api_v1_projects__project_id__edit_lock_get"];
  };
  "/api/v1/projects/{project_id}/edit-lock/acquire": {
    /** Acquire Edit Lock */
    post: operations["acquire_edit_lock_api_v1_projects__project_id__edit_lock_acquire_post"];
  };
  "/api/v1/projects/{project_id}/edit-lock/release": {
    /** Release Edit Lock */
    post: operations["release_edit_lock_api_v1_projects__project_id__edit_lock_release_post"];
  };
  "/api/v1/projects/{project_id}/edit-lock/keepalive": {
    /** Keepalive Edit Lock */
    post: operations["keepalive_edit_lock_api_v1_projects__project_id__edit_lock_keepalive_post"];
  };
  "/api/v1/projects/{project_id}/snapshots/": {
    /** List Snapshots */
    get: operations["list_snapshots_api_v1_projects__project_id__snapshots__get"];
    /** Create Snapshot */
    post: operations["create_snapshot_api_v1_projects__project_id__snapshots__post"];
  };
  "/api/v1/projects/{project_id}/snapshots/diff": {
    /**
     * Diff Snapshot
     * @description Diff the live project against a snapshot (latest when snapshot_id omitted).
     *
     * Pass ``pi_id`` to scope the diff to a single PI (including items moved into or
     * out of it). Returns per-entity added/removed/changed lists, a summary with an
     * effort delta, and a natural-language narrative.
     */
    get: operations["diff_snapshot_api_v1_projects__project_id__snapshots_diff_get"];
  };
  "/api/v1/projects/{project_id}/snapshots/diff/html": {
    /**
     * Diff Snapshot Html
     * @description Self-contained HTML rendering of the snapshot diff (twin of /diff).
     */
    get: operations["diff_snapshot_html_api_v1_projects__project_id__snapshots_diff_html_get"];
  };
  "/api/v1/projects/{project_id}/snapshots/{snapshot_id}": {
    /** Delete Snapshot */
    delete: operations["delete_snapshot_api_v1_projects__project_id__snapshots__snapshot_id__delete"];
  };
  "/api/v1/projects/{project_id}/snapshots/{snapshot_id}/restore": {
    /** Restore Snapshot */
    post: operations["restore_snapshot_api_v1_projects__project_id__snapshots__snapshot_id__restore_post"];
  };
  "/api/v1/projects/{project_id}/states/": {
    /**
     * List Project States
     * @description All three State Lists for the project, ordered by item type then position.
     */
    get: operations["list_project_states_api_v1_projects__project_id__states__get"];
    /**
     * Create Project State
     * @description Add a State to a list. Refused when the list already holds this value.
     */
    post: operations["create_project_state_api_v1_projects__project_id__states__post"];
  };
  "/api/v1/projects/{project_id}/states/{state_id}": {
    /**
     * Delete Project State
     * @description Remove a State from its list. Refused while any item still holds it.
     */
    delete: operations["delete_project_state_api_v1_projects__project_id__states__state_id__delete"];
    /**
     * Rename Project State
     * @description Rename a State. Items reference it by id, so every one of them follows.
     */
    patch: operations["rename_project_state_api_v1_projects__project_id__states__state_id__patch"];
  };
  "/api/v1/projects/{project_id}/states/reorder": {
    /**
     * Reorder Project States
     * @description Set the display order of one list. The other two lists are untouched.
     */
    post: operations["reorder_project_states_api_v1_projects__project_id__states_reorder_post"];
  };
  "/api/v1/projects/{project_id}/events": {
    /** Project Events */
    get: operations["project_events_api_v1_projects__project_id__events_get"];
  };
  "/api/v1/projects/{project_id}/import/csv": {
    /** Import Csv */
    post: operations["import_csv_api_v1_projects__project_id__import_csv_post"];
  };
  "/api/v1/api-keys/my-keys": {
    /** List My Keys */
    get: operations["list_my_keys_api_v1_api_keys_my_keys_get"];
  };
  "/api/v1/api-keys/my-activities": {
    /** List My Activities */
    get: operations["list_my_activities_api_v1_api_keys_my_activities_get"];
  };
  "/api/v1/api-keys/admin/keys": {
    /** Create Key */
    post: operations["create_key_api_v1_api_keys_admin_keys_post"];
  };
  "/api/v1/api-keys/admin/cycle/{key_id}": {
    /** Cycle Key */
    post: operations["cycle_key_api_v1_api_keys_admin_cycle__key_id__post"];
  };
  "/api/v1/api-keys/admin/keys/{key_id}": {
    /** Revoke Key */
    delete: operations["revoke_key_api_v1_api_keys_admin_keys__key_id__delete"];
  };
  "/api/v1/api-keys/admin/all-keys": {
    /** List All Keys */
    get: operations["list_all_keys_api_v1_api_keys_admin_all_keys_get"];
  };
  "/api/v1/api-keys/admin/activities": {
    /** List All Activities */
    get: operations["list_all_activities_api_v1_api_keys_admin_activities_get"];
  };
  "/api/v1/api-keys/admin/verify": {
    /**
     * Verify Key
     * @description Verify an API key token on behalf of the MCP server.
     *
     * Protected by a short-lived HS256 service JWT — not the normal session cookie.
     * Returns the username and role associated with the key.
     */
    post: operations["verify_key_api_v1_api_keys_admin_verify_post"];
  };
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** APIKeyCreate */
    APIKeyCreate: {
      /** Username */
      username: string;
      /** Name */
      name: string;
      /** Purpose */
      purpose?: string | null;
      /** Expires In Days */
      expires_in_days?: number | null;
    };
    /** APIKeyCreateResponse */
    APIKeyCreateResponse: {
      /** Id */
      id: string;
      /** Full Token */
      full_token: string;
      /** Username */
      username: string;
      /** Name */
      name: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Expires At */
      expires_at: string | null;
    };
    /** APIKeyResponse */
    APIKeyResponse: {
      /** Id */
      id: string;
      /** Username */
      username: string;
      /** Name */
      name: string;
      /** Purpose */
      purpose: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Expires At */
      expires_at: string | null;
      /** Last Used At */
      last_used_at: string | null;
      /** Is Active */
      is_active: boolean;
    };
    /** APIKeyVerifyRequest */
    APIKeyVerifyRequest: {
      /** Token */
      token: string;
    };
    /** APIKeyVerifyResponse */
    APIKeyVerifyResponse: {
      /** Username */
      username: string;
      role: components["schemas"]["Role"];
      /** Key Id */
      key_id: string;
    };
    /** ActivityLogResponse */
    ActivityLogResponse: {
      /** Id */
      id: number;
      actor_type: components["schemas"]["ActorType"];
      /** Actor Username */
      actor_username: string;
      /** Api Key Id */
      api_key_id: string | null;
      /** Action */
      action: string;
      /** Resource Type */
      resource_type: string | null;
      /** Resource Id */
      resource_id: string | null;
      /** Project Id */
      project_id: string | null;
      /** Details */
      details: {
        [key: string]: unknown;
      } | null;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /** Status */
      status: string;
    };
    /**
     * ActorType
     * @enum {string}
     */
    ActorType: "human" | "mcp_bot";
    /** Body_import_project_api_v1_projects_import_post */
    Body_import_project_api_v1_projects_import_post: {
      /** File */
      file: string;
    };
    /** BulkDeleteResponse */
    BulkDeleteResponse: {
      /** Deleted Features */
      deleted_features: number;
    };
    /** ChangePassword */
    ChangePassword: {
      /** Old Password */
      old_password: string;
      /** New Password */
      new_password: string;
    };
    /** CsvImportRequest */
    CsvImportRequest: {
      /** Rows */
      rows: components["schemas"]["CsvRow"][];
      /**
       * Removals
       * @default []
       */
      removals?: string[];
      /**
       * Has State Column
       * @default false
       */
      has_state_column?: boolean;
    };
    /** CsvImportResult */
    CsvImportResult: {
      /** Created Features */
      created_features: number;
      /** Created Stories */
      created_stories: number;
      /** Updated Features */
      updated_features: number;
      /** Updated Stories */
      updated_stories: number;
      /** Removed Features */
      removed_features: number;
      /** Removed Stories */
      removed_stories: number;
      /** Orphan Stories */
      orphan_stories: number;
      /**
       * Orphan Stories Placed
       * @default 0
       */
      orphan_stories_placed?: number;
      /**
       * Orphan Stories Existing
       * @default []
       */
      orphan_stories_existing?: components["schemas"]["OrphanLocation"][];
      /**
       * Created States
       * @default 0
       */
      created_states?: number;
    };
    /** CsvRow */
    CsvRow: {
      /** Row Number */
      row_number: number;
      /** Item Type */
      item_type: string;
      /** User Id */
      user_id?: number | null;
      /** Title */
      title: string;
      /** Effort */
      effort?: number | null;
      /** Parent Id */
      parent_id?: number | null;
      /** State */
      state?: string | null;
    };
    /** EditLockResponse */
    EditLockResponse: {
      /** Project Id */
      project_id: string;
      /** Locked By Username */
      locked_by_username: string | null;
      /** Locked At */
      locked_at: string | null;
      /** Expires At */
      expires_at: string | null;
      /** Is Locked */
      is_locked: boolean;
    };
    /** FeatureCreate */
    FeatureCreate: {
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /** Id */
      id?: number | null;
      /** State Id */
      state_id?: string | null;
    };
    /** FeatureResponse */
    FeatureResponse: {
      /** System Id */
      system_id: string;
      /** Id */
      id?: number | null;
      /** Title */
      title: string;
      /** Description */
      description: string | null;
      /**
       * Effort
       * @default 0
       */
      effort?: number;
      /** Location */
      location: string;
      /** Pi Id */
      pi_id: string | null;
      /** Swimlane Id */
      swimlane_id: string | null;
      /** Continued From Feature Id */
      continued_from_feature_id: string | null;
      /** State Id */
      state_id?: string | null;
      /** State */
      state?: string | null;
      /** Project Id */
      project_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** FeatureSplitRequest */
    FeatureSplitRequest: {
      /** Target Pi Id */
      target_pi_id: string;
      /** Target Swimline Id */
      target_swimline_id: string;
      /** Pbi Ids */
      pbi_ids: string[];
    };
    /** FeatureUpdate */
    FeatureUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Id */
      id?: number | null;
      /** Location */
      location?: ("backlog" | "pi") | null;
      /** Pi Id */
      pi_id?: string | null;
      /** Swimlane Id */
      swimlane_id?: string | null;
      /** State Id */
      state_id?: string | null;
    };
    /** GroupCreate */
    GroupCreate: {
      /** Name */
      name: string;
      /** Feature System Id */
      feature_system_id: string;
      /** Pbi Ids */
      pbi_ids?: string[];
      /** Sprint Index */
      sprint_index?: number | null;
      /** Order Index */
      order_index?: number | null;
      /**
       * Is Implicit
       * @default false
       */
      is_implicit?: boolean;
      /** Story System Id */
      story_system_id?: string | null;
    };
    /** GroupResponse */
    GroupResponse: {
      /** System Id */
      system_id: string;
      /** Swimline Id */
      swimline_id: string;
      /** Feature System Id */
      feature_system_id: string;
      /** Name */
      name: string;
      /** Sprint Index */
      sprint_index: number | null;
      /** Order Index */
      order_index: number | null;
      /** Is Implicit */
      is_implicit: boolean;
      /** Story System Id */
      story_system_id: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** GroupUpdate */
    GroupUpdate: {
      /** Name */
      name?: string | null;
      /** Sprint Index */
      sprint_index?: number | null;
      /** Order Index */
      order_index?: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginRequest */
    LoginRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Remember Me
       * @default false
       */
      remember_me?: boolean;
    };
    /**
     * OrphanLocation
     * @description Where orphan rows that matched an existing story already live.
     */
    OrphanLocation: {
      /** Feature Title */
      feature_title: string;
      /** Location */
      location: string;
      /** Count */
      count: number;
    };
    /** PBICreate */
    PBICreate: {
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /** Effort */
      effort?: number | null;
      /** Id */
      id?: number | null;
      /** Parent Feature System Id */
      parent_feature_system_id: string;
      /**
       * Item Type
       * @default story
       * @enum {string}
       */
      item_type?: "story" | "bug";
      /** State Id */
      state_id?: string | null;
    };
    /** PBIResponse */
    PBIResponse: {
      /** System Id */
      system_id: string;
      /** Id */
      id?: number | null;
      /** Parent Feature System Id */
      parent_feature_system_id: string;
      /** Title */
      title: string;
      /** Description */
      description: string | null;
      /** Effort */
      effort: number | null;
      /**
       * Item Type
       * @enum {string}
       */
      item_type: "story" | "bug";
      /** Location */
      location: string;
      /** Pi Id */
      pi_id: string | null;
      /** Swimlane Id */
      swimlane_id: string | null;
      /** Group Id */
      group_id: string | null;
      /** State Id */
      state_id?: string | null;
      /** State */
      state?: string | null;
      /** Project Id */
      project_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** PBIUpdate */
    PBIUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Effort */
      effort?: number | null;
      /** Id */
      id?: number | null;
      /** Item Type */
      item_type?: ("story" | "bug") | null;
      /** Location */
      location?: ("backlog" | "pi") | null;
      /** Pi Id */
      pi_id?: string | null;
      /** Swimlane Id */
      swimlane_id?: string | null;
      /** Group Id */
      group_id?: string | null;
      /** State Id */
      state_id?: string | null;
    };
    /** PICreate */
    PICreate: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * State
       * @default draft
       * @enum {string}
       */
      state?: "draft" | "in_progress" | "closed";
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
    };
    /** PIEventCreate */
    PIEventCreate: {
      /** Name */
      name: string;
      /**
       * Event Date
       * Format: date
       */
      event_date: string;
      /**
       * Event Type
       * @enum {string}
       */
      event_type: "release" | "milestone" | "deadline" | "pilot" | "go_no_go" | "other";
    };
    /** PIEventResponse */
    PIEventResponse: {
      /** System Id */
      system_id: string;
      /** Pi Id */
      pi_id: string;
      /** Name */
      name: string;
      /**
       * Event Date
       * Format: date
       */
      event_date: string;
      /**
       * Event Type
       * @enum {string}
       */
      event_type: "release" | "milestone" | "deadline" | "pilot" | "go_no_go" | "other";
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** PIEventUpdate */
    PIEventUpdate: {
      /** Name */
      name?: string | null;
      /** Event Date */
      event_date?: string | null;
      /** Event Type */
      event_type?: ("release" | "milestone" | "deadline" | "pilot" | "go_no_go" | "other") | null;
    };
    /** PIResponse */
    PIResponse: {
      /** System Id */
      system_id: string;
      /** Project Id */
      project_id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** State */
      state: string;
      /** Start Date */
      start_date: string | null;
      /** End Date */
      end_date: string | null;
      /**
       * Total Effort
       * @default 0
       */
      total_effort?: number;
      /**
       * Total Capacity
       * @default 0
       */
      total_capacity?: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** PIUpdate */
    PIUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** State */
      state?: ("draft" | "in_progress" | "closed") | null;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
    };
    /** PasswordReset */
    PasswordReset: {
      /** New Password */
      new_password: string;
    };
    /** PlaceStoryRequest */
    PlaceStoryRequest: {
      /** Sprint Index */
      sprint_index: number;
    };
    /** PlaceStoryResponse */
    PlaceStoryResponse: {
      story: components["schemas"]["PBIResponse"];
      group: components["schemas"]["GroupResponse"];
    };
    /** ProjectCreate */
    ProjectCreate: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Azure Devops Url */
      azure_devops_url?: string | null;
      /** Work Item Path Template */
      work_item_path_template?: string | null;
    };
    /** ProjectResponse */
    ProjectResponse: {
      /** System Id */
      system_id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Azure Devops Url */
      azure_devops_url: string | null;
      /** Work Item Path Template */
      work_item_path_template: string | null;
      /** Effort Unit */
      effort_unit: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** ProjectStateCreate */
    ProjectStateCreate: {
      /**
       * Item Type
       * @enum {string}
       */
      item_type: "feature" | "story" | "bug";
      /** Value */
      value: string;
    };
    /**
     * ProjectStateReorder
     * @description The new order of one list. The three lists are ordered independently.
     */
    ProjectStateReorder: {
      /**
       * Item Type
       * @enum {string}
       */
      item_type: "feature" | "story" | "bug";
      /**
       * Order
       * @description Ordered list of State system_ids
       */
      order: string[];
    };
    /** ProjectStateResponse */
    ProjectStateResponse: {
      /** System Id */
      system_id: string;
      /** Project Id */
      project_id: string;
      /**
       * Item Type
       * @enum {string}
       */
      item_type: "feature" | "story" | "bug";
      /** Value */
      value: string;
      /** Position */
      position: number;
      /** Category */
      category?: ("not_started" | "in_progress" | "done") | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ProjectStateUpdate
     * @description Rename one entry. Every item holding it follows, since items reference by id.
     */
    ProjectStateUpdate: {
      /** Value */
      value: string;
    };
    /** ProjectUpdate */
    ProjectUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Azure Devops Url */
      azure_devops_url?: string | null;
      /** Work Item Path Template */
      work_item_path_template?: string | null;
      /** Effort Unit */
      effort_unit?: string | null;
    };
    /**
     * Role
     * @enum {string}
     */
    Role: "admin" | "editor" | "reader";
    /** SnapshotCreate */
    SnapshotCreate: {
      /** Name */
      name: string;
    };
    /**
     * SnapshotDiffResponse
     * @description Structured diff of the live project against a baseline snapshot.
     *
     * ``changes`` holds per-entity-type ``{added, removed, changed}`` lists;
     * ``summary`` holds the matching counts plus a ``total_effort`` delta;
     * ``labels`` maps id references (pi/swimline) to names for rendering; and
     * ``narrative`` is a compact human/LLM-readable summary. See
     * ``app.services.snapshot_diff`` for the exact shapes.
     */
    SnapshotDiffResponse: {
      /** Baseline Snapshot */
      baseline_snapshot: {
        [key: string]: unknown;
      };
      /** Compared At */
      compared_at: string;
      /** Scope */
      scope: {
        [key: string]: unknown;
      };
      /** Summary */
      summary: {
        [key: string]: unknown;
      };
      /** Changes */
      changes: {
        [key: string]: unknown;
      };
      /** Labels */
      labels: {
        [key: string]: unknown;
      };
      /** Narrative */
      narrative: string;
    };
    /** SnapshotResponse */
    SnapshotResponse: {
      /** System Id */
      system_id: string;
      /** Name */
      name: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string | null;
    };
    /** SprintResponse */
    SprintResponse: {
      /** System Id */
      system_id: string;
      /** Pi Id */
      pi_id: string;
      /** Sprint Index */
      sprint_index: number | null;
      /** Capacity */
      capacity: number;
      /**
       * Effort
       * @default 0
       */
      effort?: number;
      /** Start Date */
      start_date: string | null;
      /** End Date */
      end_date: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** SprintUpdate */
    SprintUpdate: {
      /** Capacity */
      capacity?: number | null;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
    };
    /** SwimlineCreate */
    SwimlineCreate: {
      /** Name */
      name: string;
      /** Order Index */
      order_index?: number | null;
    };
    /** SwimlineReorder */
    SwimlineReorder: {
      /**
       * Order
       * @description Ordered list of swimline system_ids
       */
      order: string[];
    };
    /** SwimlineResponse */
    SwimlineResponse: {
      /** System Id */
      system_id: string;
      /** Pi Id */
      pi_id: string;
      /** Name */
      name: string;
      /** Order Index */
      order_index: number | null;
      /**
       * Effort
       * @default 0
       */
      effort?: number;
      /**
       * Capacity
       * @default 0
       */
      capacity?: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** SwimlineUpdate */
    SwimlineUpdate: {
      /** Name */
      name?: string | null;
      /** Order Index */
      order_index?: number | null;
    };
    /** TokenResponse */
    TokenResponse: {
      user: components["schemas"]["UserResponse"];
    };
    /** UserCreate */
    UserCreate: {
      /** Username */
      username: string;
      /** Display Name */
      display_name?: string | null;
      role: components["schemas"]["Role"];
      /** Password */
      password: string;
    };
    /** UserResponse */
    UserResponse: {
      /** Username */
      username: string;
      /** Display Name */
      display_name: string | null;
      /**
       * Role
       * @enum {string}
       */
      role: "admin" | "editor" | "reader";
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Last Login At */
      last_login_at: string | null;
      /** Password Changed At */
      password_changed_at: string | null;
    };
    /** UserUpdate */
    UserUpdate: {
      /** Display Name */
      display_name?: string | null;
      role?: components["schemas"]["Role"] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Login */
  login_api_v1_auth_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Logout */
  logout_api_v1_auth_logout_post: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Me */
  me_api_v1_auth_me_get: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Change Password */
  change_password_api_v1_auth_change_password_post: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePassword"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Users */
  list_users_api_v1_users__get: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create User */
  create_user_api_v1_users__post: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update User */
  update_user_api_v1_users__username__put: {
    parameters: {
      path: {
        username: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete User */
  delete_user_api_v1_users__username__delete: {
    parameters: {
      path: {
        username: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reset Password */
  reset_password_api_v1_users__username__reset_password_post: {
    parameters: {
      path: {
        username: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordReset"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Projects */
  list_projects_api_v1_projects__get: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Project */
  create_project_api_v1_projects__post: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Project */
  get_project_api_v1_projects__project_id__get: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Project */
  delete_project_api_v1_projects__project_id__delete: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Project */
  update_project_api_v1_projects__project_id__patch: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Import Project */
  import_project_api_v1_projects_import_post: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_import_project_api_v1_projects_import_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Invalid or malformed import payload */
      422: {
        content: never;
      };
    };
  };
  /** Export Project */
  export_project_api_v1_projects__project_id__export_get: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Features */
  list_features_api_v1_projects__project_id__features_get: {
    parameters: {
      query?: {
        sort?: string;
      };
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Feature */
  create_feature_api_v1_projects__project_id__features_post: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeatureCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["FeatureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Clear All Features */
  clear_all_features_api_v1_projects__project_id__features_delete: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BulkDeleteResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Feature */
  get_feature_api_v1_features__feature_id__get: {
    parameters: {
      path: {
        feature_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Feature */
  delete_feature_api_v1_features__feature_id__delete: {
    parameters: {
      path: {
        feature_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Feature */
  update_feature_api_v1_features__feature_id__patch: {
    parameters: {
      path: {
        feature_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeatureUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Split Feature */
  split_feature_api_v1_features__feature_id__split_post: {
    parameters: {
      path: {
        feature_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeatureSplitRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Cancel Continuation */
  cancel_continuation_api_v1_features__feature_id__cancel_continuation_post: {
    parameters: {
      path: {
        feature_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Clear Backlog */
  clear_backlog_api_v1_projects__project_id__backlog_delete: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BulkDeleteResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Pbis */
  list_pbis_api_v1_projects__project_id__pbis_get: {
    parameters: {
      query?: {
        feature_id?: string | null;
      };
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PBIResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Pbi */
  create_pbi_api_v1_projects__project_id__pbis_post: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PBICreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PBIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Pbi */
  get_pbi_api_v1_pbis__pbi_id__get: {
    parameters: {
      path: {
        pbi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PBIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Pbi */
  delete_pbi_api_v1_pbis__pbi_id__delete: {
    parameters: {
      path: {
        pbi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Pbi */
  update_pbi_api_v1_pbis__pbi_id__patch: {
    parameters: {
      path: {
        pbi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PBIUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PBIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Place Story In Sprint */
  place_story_in_sprint_api_v1_pbis__pbi_id__place_post: {
    parameters: {
      path: {
        pbi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaceStoryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PlaceStoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Unplace Story */
  unplace_story_api_v1_pbis__pbi_id__place_delete: {
    parameters: {
      path: {
        pbi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Events */
  list_events_api_v1_pis__pi_id__events_get: {
    parameters: {
      path: {
        pi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PIEventResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Event */
  create_event_api_v1_pis__pi_id__events_post: {
    parameters: {
      path: {
        pi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PIEventCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PIEventResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Event */
  delete_event_api_v1_pis__pi_id__events__event_id__delete: {
    parameters: {
      path: {
        pi_id: string;
        event_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Event */
  update_event_api_v1_pis__pi_id__events__event_id__patch: {
    parameters: {
      path: {
        pi_id: string;
        event_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PIEventUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PIEventResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Pis */
  list_pis_api_v1_projects__project_id__pis_get: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PIResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Pi */
  create_pi_api_v1_projects__project_id__pis_post: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PICreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Pi */
  get_pi_api_v1_pis__pi_id__get: {
    parameters: {
      path: {
        pi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Pi */
  delete_pi_api_v1_pis__pi_id__delete: {
    parameters: {
      path: {
        pi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Pi */
  update_pi_api_v1_pis__pi_id__patch: {
    parameters: {
      path: {
        pi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PIUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Export Pi Csv Endpoint */
  export_pi_csv_endpoint_api_v1_pis__pi_id__export_csv_get: {
    parameters: {
      path: {
        pi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Export Pi Png Endpoint */
  export_pi_png_endpoint_api_v1_pis__pi_id__export_png_get: {
    parameters: {
      query?: {
        layout?: string;
        show_pi_effort?: boolean;
        show_sprint_effort?: boolean;
        show_swimlane_effort?: boolean;
        show_events?: boolean;
        swimlane_text_center?: boolean;
        show_export_date?: boolean;
        split_by_swimline?: boolean;
        show_id?: boolean;
      };
      path: {
        pi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Export Pi Report Endpoint */
  export_pi_report_endpoint_api_v1_pis__pi_id__report_get: {
    parameters: {
      query?: {
        report_type?: string;
        fmt?: string;
        show_ids?: boolean;
      };
      path: {
        pi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Export Pi Dashboard Endpoint */
  export_pi_dashboard_endpoint_api_v1_pis__pi_id__export_html_get: {
    parameters: {
      query?: {
        refresh_seconds?: number;
        show_ids?: boolean;
      };
      path: {
        pi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Swimlines */
  list_swimlines_api_v1_pis__pi_id__swimlines_get: {
    parameters: {
      path: {
        pi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SwimlineResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Swimline */
  create_swimline_api_v1_pis__pi_id__swimlines_post: {
    parameters: {
      path: {
        pi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SwimlineCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SwimlineResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Swimline */
  get_swimline_api_v1_swimlines__swimline_id__get: {
    parameters: {
      path: {
        swimline_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SwimlineResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Swimline */
  delete_swimline_api_v1_swimlines__swimline_id__delete: {
    parameters: {
      path: {
        swimline_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Swimline */
  update_swimline_api_v1_swimlines__swimline_id__patch: {
    parameters: {
      path: {
        swimline_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SwimlineUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SwimlineResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reorder Swimlines */
  reorder_swimlines_api_v1_swimlines__swimline_id__reorder_post: {
    parameters: {
      path: {
        swimline_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SwimlineReorder"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SwimlineResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Groups */
  list_groups_api_v1_swimlines__swimline_id__groups_get: {
    parameters: {
      path: {
        swimline_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GroupResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Group */
  create_group_api_v1_swimlines__swimline_id__groups_post: {
    parameters: {
      path: {
        swimline_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GroupCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["GroupResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Group */
  get_group_api_v1_groups__group_id__get: {
    parameters: {
      path: {
        group_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GroupResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Group */
  delete_group_api_v1_groups__group_id__delete: {
    parameters: {
      path: {
        group_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Group */
  update_group_api_v1_groups__group_id__patch: {
    parameters: {
      path: {
        group_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GroupUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GroupResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Sprints */
  list_sprints_api_v1_pis__pi_id__sprints_get: {
    parameters: {
      path: {
        pi_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SprintResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Sprint */
  update_sprint_api_v1_sprints__sprint_id__patch: {
    parameters: {
      path: {
        sprint_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SprintUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SprintResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Edit Lock */
  get_edit_lock_api_v1_projects__project_id__edit_lock_get: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EditLockResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Acquire Edit Lock */
  acquire_edit_lock_api_v1_projects__project_id__edit_lock_acquire_post: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EditLockResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Release Edit Lock */
  release_edit_lock_api_v1_projects__project_id__edit_lock_release_post: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Keepalive Edit Lock */
  keepalive_edit_lock_api_v1_projects__project_id__edit_lock_keepalive_post: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EditLockResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Snapshots */
  list_snapshots_api_v1_projects__project_id__snapshots__get: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SnapshotResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Snapshot */
  create_snapshot_api_v1_projects__project_id__snapshots__post: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SnapshotCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SnapshotResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Diff Snapshot
   * @description Diff the live project against a snapshot (latest when snapshot_id omitted).
   *
   * Pass ``pi_id`` to scope the diff to a single PI (including items moved into or
   * out of it). Returns per-entity added/removed/changed lists, a summary with an
   * effort delta, and a natural-language narrative.
   */
  diff_snapshot_api_v1_projects__project_id__snapshots_diff_get: {
    parameters: {
      query?: {
        snapshot_id?: string | null;
        pi_id?: string | null;
      };
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SnapshotDiffResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Diff Snapshot Html
   * @description Self-contained HTML rendering of the snapshot diff (twin of /diff).
   */
  diff_snapshot_html_api_v1_projects__project_id__snapshots_diff_html_get: {
    parameters: {
      query?: {
        snapshot_id?: string | null;
        pi_id?: string | null;
        refresh_seconds?: number;
      };
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "text/html": string;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Snapshot */
  delete_snapshot_api_v1_projects__project_id__snapshots__snapshot_id__delete: {
    parameters: {
      path: {
        project_id: string;
        snapshot_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Restore Snapshot */
  restore_snapshot_api_v1_projects__project_id__snapshots__snapshot_id__restore_post: {
    parameters: {
      path: {
        project_id: string;
        snapshot_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Project States
   * @description All three State Lists for the project, ordered by item type then position.
   */
  list_project_states_api_v1_projects__project_id__states__get: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectStateResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Project State
   * @description Add a State to a list. Refused when the list already holds this value.
   */
  create_project_state_api_v1_projects__project_id__states__post: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectStateCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ProjectStateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Project State
   * @description Remove a State from its list. Refused while any item still holds it.
   */
  delete_project_state_api_v1_projects__project_id__states__state_id__delete: {
    parameters: {
      path: {
        project_id: string;
        state_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Rename Project State
   * @description Rename a State. Items reference it by id, so every one of them follows.
   */
  rename_project_state_api_v1_projects__project_id__states__state_id__patch: {
    parameters: {
      path: {
        project_id: string;
        state_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectStateUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectStateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Reorder Project States
   * @description Set the display order of one list. The other two lists are untouched.
   */
  reorder_project_states_api_v1_projects__project_id__states_reorder_post: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectStateReorder"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectStateResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Project Events */
  project_events_api_v1_projects__project_id__events_get: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Import Csv */
  import_csv_api_v1_projects__project_id__import_csv_post: {
    parameters: {
      path: {
        project_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CsvImportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CsvImportResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List My Keys */
  list_my_keys_api_v1_api_keys_my_keys_get: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["APIKeyResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List My Activities */
  list_my_activities_api_v1_api_keys_my_activities_get: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ActivityLogResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Key */
  create_key_api_v1_api_keys_admin_keys_post: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["APIKeyCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["APIKeyCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Cycle Key */
  cycle_key_api_v1_api_keys_admin_cycle__key_id__post: {
    parameters: {
      path: {
        key_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["APIKeyCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Revoke Key */
  revoke_key_api_v1_api_keys_admin_keys__key_id__delete: {
    parameters: {
      path: {
        key_id: string;
      };
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List All Keys */
  list_all_keys_api_v1_api_keys_admin_all_keys_get: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["APIKeyResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List All Activities */
  list_all_activities_api_v1_api_keys_admin_activities_get: {
    parameters: {
      cookie?: {
        pi_session?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ActivityLogResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Verify Key
   * @description Verify an API key token on behalf of the MCP server.
   *
   * Protected by a short-lived HS256 service JWT — not the normal session cookie.
   * Returns the username and role associated with the key.
   */
  verify_key_api_v1_api_keys_admin_verify_post: {
    parameters: {
      header?: {
        authorization?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["APIKeyVerifyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["APIKeyVerifyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
