/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/login": {
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
  };
  "/api/v1/auth/logout": {
    /** Logout */
    post: operations["logout_api_v1_auth_logout_post"];
  };
  "/api/v1/auth/me": {
    /** Me */
    get: operations["me_api_v1_auth_me_get"];
  };
  "/api/v1/projects/": {
    /** List Projects */
    get: operations["list_projects_api_v1_projects__get"];
    /** Create Project */
    post: operations["create_project_api_v1_projects__post"];
  };
  "/api/v1/projects/{project_id}": {
    /** Get Project */
    get: operations["get_project_api_v1_projects__project_id__get"];
    /** Delete Project */
    delete: operations["delete_project_api_v1_projects__project_id__delete"];
    /** Update Project */
    patch: operations["update_project_api_v1_projects__project_id__patch"];
  };
  "/api/v1/projects/{project_id}/features": {
    /** List Features */
    get: operations["list_features_api_v1_projects__project_id__features_get"];
    /** Create Feature */
    post: operations["create_feature_api_v1_projects__project_id__features_post"];
  };
  "/api/v1/features/{feature_id}": {
    /** Get Feature */
    get: operations["get_feature_api_v1_features__feature_id__get"];
    /** Delete Feature */
    delete: operations["delete_feature_api_v1_features__feature_id__delete"];
    /** Update Feature */
    patch: operations["update_feature_api_v1_features__feature_id__patch"];
  };
  "/api/v1/projects/{project_id}/pbis": {
    /** List Pbis */
    get: operations["list_pbis_api_v1_projects__project_id__pbis_get"];
    /** Create Pbi */
    post: operations["create_pbi_api_v1_projects__project_id__pbis_post"];
  };
  "/api/v1/pbis/{pbi_id}": {
    /** Get Pbi */
    get: operations["get_pbi_api_v1_pbis__pbi_id__get"];
    /** Delete Pbi */
    delete: operations["delete_pbi_api_v1_pbis__pbi_id__delete"];
    /** Update Pbi */
    patch: operations["update_pbi_api_v1_pbis__pbi_id__patch"];
  };
  "/api/v1/projects/{project_id}/pis": {
    /** List Pis */
    get: operations["list_pis_api_v1_projects__project_id__pis_get"];
    /** Create Pi */
    post: operations["create_pi_api_v1_projects__project_id__pis_post"];
  };
  "/api/v1/pis/{pi_id}": {
    /** Get Pi */
    get: operations["get_pi_api_v1_pis__pi_id__get"];
    /** Delete Pi */
    delete: operations["delete_pi_api_v1_pis__pi_id__delete"];
    /** Update Pi */
    patch: operations["update_pi_api_v1_pis__pi_id__patch"];
  };
  "/api/v1/pis/{pi_id}/swimlines": {
    /** List Swimlines */
    get: operations["list_swimlines_api_v1_pis__pi_id__swimlines_get"];
    /** Create Swimline */
    post: operations["create_swimline_api_v1_pis__pi_id__swimlines_post"];
  };
  "/api/v1/swimlines/{swimline_id}": {
    /** Get Swimline */
    get: operations["get_swimline_api_v1_swimlines__swimline_id__get"];
    /** Delete Swimline */
    delete: operations["delete_swimline_api_v1_swimlines__swimline_id__delete"];
    /** Update Swimline */
    patch: operations["update_swimline_api_v1_swimlines__swimline_id__patch"];
  };
  "/api/v1/swimlines/{swimline_id}/groups": {
    /** List Groups */
    get: operations["list_groups_api_v1_swimlines__swimline_id__groups_get"];
    /** Create Group */
    post: operations["create_group_api_v1_swimlines__swimline_id__groups_post"];
  };
  "/api/v1/groups/{group_id}": {
    /** Get Group */
    get: operations["get_group_api_v1_groups__group_id__get"];
    /** Delete Group */
    delete: operations["delete_group_api_v1_groups__group_id__delete"];
    /** Update Group */
    patch: operations["update_group_api_v1_groups__group_id__patch"];
  };
  "/api/v1/pis/{pi_id}/sprints": {
    /** List Sprints */
    get: operations["list_sprints_api_v1_pis__pi_id__sprints_get"];
    /** Create Sprint */
    post: operations["create_sprint_api_v1_pis__pi_id__sprints_post"];
  };
  "/api/v1/sprints/{sprint_id}": {
    /** Update Sprint */
    patch: operations["update_sprint_api_v1_sprints__sprint_id__patch"];
  };
  "/api/v1/projects/{project_id}/edit-lock": {
    /** Get Edit Lock */
    get: operations["get_edit_lock_api_v1_projects__project_id__edit_lock_get"];
  };
  "/api/v1/projects/{project_id}/edit-lock/acquire": {
    /** Acquire Edit Lock */
    post: operations["acquire_edit_lock_api_v1_projects__project_id__edit_lock_acquire_post"];
  };
  "/api/v1/projects/{project_id}/edit-lock/release": {
    /** Release Edit Lock */
    post: operations["release_edit_lock_api_v1_projects__project_id__edit_lock_release_post"];
  };
  "/api/v1/projects/{project_id}/edit-lock/keepalive": {
    /** Keepalive Edit Lock */
    post: operations["keepalive_edit_lock_api_v1_projects__project_id__edit_lock_keepalive_post"];
  };
  "/api/v1/projects/{project_id}/events": {
    /** Project Events */
    get: operations["project_events_api_v1_projects__project_id__events_get"];
  };
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** EditLockResponse */
    EditLockResponse: {
      /** Project Id */
      project_id: string;
      /** Locked By Username */
      locked_by_username: string | null;
      /** Locked At */
      locked_at: string | null;
      /** Expires At */
      expires_at: string | null;
      /** Is Locked */
      is_locked: boolean;
    };
    /** FeatureCreate */
    FeatureCreate: {
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /** Effort */
      effort?: number | null;
      /** Id */
      id?: number | null;
    };
    /** FeatureResponse */
    FeatureResponse: {
      /** System Id */
      system_id: string;
      /** Id */
      id?: number | null;
      /** Title */
      title: string;
      /** Description */
      description: string | null;
      /** Effort */
      effort: number | null;
      /** Location */
      location: string;
      /** Pi Id */
      pi_id: string | null;
      /** Swimlane Id */
      swimlane_id: string | null;
      /** Project Id */
      project_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** FeatureUpdate */
    FeatureUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Effort */
      effort?: number | null;
      /** Id */
      id?: number | null;
      /** Location */
      location?: ("backlog" | "pi") | null;
      /** Pi Id */
      pi_id?: string | null;
      /** Swimlane Id */
      swimlane_id?: string | null;
    };
    /** GroupCreate */
    GroupCreate: {
      /** Name */
      name: string;
      /** Feature System Id */
      feature_system_id: string;
      /** Sprint Index */
      sprint_index?: number | null;
      /** Order Index */
      order_index?: number | null;
    };
    /** GroupResponse */
    GroupResponse: {
      /** System Id */
      system_id: string;
      /** Swimline Id */
      swimline_id: string;
      /** Feature System Id */
      feature_system_id: string;
      /** Name */
      name: string;
      /** Sprint Index */
      sprint_index: number | null;
      /** Order Index */
      order_index: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** GroupUpdate */
    GroupUpdate: {
      /** Name */
      name?: string | null;
      /** Sprint Index */
      sprint_index?: number | null;
      /** Order Index */
      order_index?: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginRequest */
    LoginRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Remember Me
       * @default false
       */
      remember_me?: boolean;
    };
    /** PBICreate */
    PBICreate: {
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /** Effort */
      effort?: number | null;
      /** Id */
      id?: number | null;
      /** Parent Feature System Id */
      parent_feature_system_id: string;
      /** Item Type */
      item_type?: "story" | "bug";
    };
    /** PBIResponse */
    PBIResponse: {
      /** System Id */
      system_id: string;
      /** Id */
      id?: number | null;
      /** Parent Feature System Id */
      parent_feature_system_id: string;
      /** Title */
      title: string;
      /** Description */
      description: string | null;
      /** Effort */
      effort: number | null;
      /** Item Type */
      item_type: "story" | "bug";
      /** Location */
      location: string;
      /** Pi Id */
      pi_id: string | null;
      /** Swimlane Id */
      swimlane_id: string | null;
      /** Group Id */
      group_id: string | null;
      /** Project Id */
      project_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** PBIUpdate */
    PBIUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Effort */
      effort?: number | null;
      /** Id */
      id?: number | null;
      /** Item Type */
      item_type?: ("story" | "bug") | null;
      /** Location */
      location?: ("backlog" | "pi") | null;
      /** Pi Id */
      pi_id?: string | null;
      /** Swimlane Id */
      swimlane_id?: string | null;
      /** Group Id */
      group_id?: string | null;
    };
    /** PICreate */
    PICreate: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * State
       * @default draft
       * @enum {string}
       */
      state?: "draft" | "in_progress" | "closed";
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
    };
    /** PIResponse */
    PIResponse: {
      /** System Id */
      system_id: string;
      /** Project Id */
      project_id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** State */
      state: string;
      /** Start Date */
      start_date: string | null;
      /** End Date */
      end_date: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** PIUpdate */
    PIUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** State */
      state?: ("draft" | "in_progress" | "closed") | null;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
    };
    /** ProjectCreate */
    ProjectCreate: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
    };
    /** ProjectResponse */
    ProjectResponse: {
      /** System Id */
      system_id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Effort Unit */
      effort_unit: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** ProjectUpdate */
    ProjectUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Effort Unit */
      effort_unit?: string | null;
    };
    /** SprintCreate */
    SprintCreate: {
      /** Sprint Index */
      sprint_index: number;
      /** Capacity */
      capacity: number;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
    };
    /** SprintResponse */
    SprintResponse: {
      /** System Id */
      system_id: string;
      /** Pi Id */
      pi_id: string;
      /** Sprint Index */
      sprint_index: number | null;
      /** Capacity */
      capacity: number;
      /** Start Date */
      start_date: string | null;
      /** End Date */
      end_date: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** SprintUpdate */
    SprintUpdate: {
      /** Capacity */
      capacity?: number | null;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
    };
    /** SwimlineCreate */
    SwimlineCreate: {
      /** Name */
      name: string;
      /** Order Index */
      order_index?: number | null;
    };
    /** SwimlineResponse */
    SwimlineResponse: {
      /** System Id */
      system_id: string;
      /** Pi Id */
      pi_id: string;
      /** Name */
      name: string;
      /** Order Index */
      order_index: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Modified At
       * Format: date-time
       */
      modified_at: string;
    };
    /** SwimlineUpdate */
    SwimlineUpdate: {
      /** Name */
      name?: string | null;
      /** Order Index */
      order_index?: number | null;
    };
    /** TokenResponse */
    TokenResponse: {
      user: components["schemas"]["UserResponse"];
      /** Session Id */
      session_id: string;
    };
    /** UserResponse */
    UserResponse: {
      /** Username */
      username: string;
      /** Display Name */
      display_name: string | null;
      /** Is Admin */
      is_admin: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** CsvRow */
    CsvRow: {
      /** Row Number */
      row_number: number;
      /** Item Type */
      item_type: "feature" | "story" | "bug";
      /** User Id */
      user_id: number | null;
      /** Title */
      title: string;
      /** Effort */
      effort: number | null;
      /** Parent Id */
      parent_id: number | null;
    };
    /** CsvImportRequest */
    CsvImportRequest: {
      /** Rows */
      rows: components["schemas"]["CsvRow"][];
    };
    /** CsvImportResult */
    CsvImportResult: {
      /** Created Features */
      created_features: number;
      /** Created Stories */
      created_stories: number;
      /** Updated Features */
      updated_features: number;
      /** Updated Stories */
      updated_stories: number;
      /** Orphan Stories */
      orphan_stories: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Login */
  login_api_v1_auth_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Logout */
  logout_api_v1_auth_logout_post: {
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
    };
  };
  /** Me */
  me_api_v1_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  /** List Projects */
  list_projects_api_v1_projects__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"][];
        };
      };
    };
  };
  /** Create Project */
  create_project_api_v1_projects__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Project */
  get_project_api_v1_projects__project_id__get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Project */
  delete_project_api_v1_projects__project_id__delete: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Project */
  update_project_api_v1_projects__project_id__patch: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Features */
  list_features_api_v1_projects__project_id__features_get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Feature */
  create_feature_api_v1_projects__project_id__features_post: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeatureCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["FeatureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Feature */
  get_feature_api_v1_features__feature_id__get: {
    parameters: {
      path: {
        feature_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Feature */
  delete_feature_api_v1_features__feature_id__delete: {
    parameters: {
      path: {
        feature_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Feature */
  update_feature_api_v1_features__feature_id__patch: {
    parameters: {
      path: {
        feature_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeatureUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FeatureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Pbis */
  list_pbis_api_v1_projects__project_id__pbis_get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PBIResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Pbi */
  create_pbi_api_v1_projects__project_id__pbis_post: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PBICreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PBIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Pbi */
  get_pbi_api_v1_pbis__pbi_id__get: {
    parameters: {
      path: {
        pbi_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PBIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Pbi */
  delete_pbi_api_v1_pbis__pbi_id__delete: {
    parameters: {
      path: {
        pbi_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Pbi */
  update_pbi_api_v1_pbis__pbi_id__patch: {
    parameters: {
      path: {
        pbi_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PBIUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PBIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Pis */
  list_pis_api_v1_projects__project_id__pis_get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PIResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Pi */
  create_pi_api_v1_projects__project_id__pis_post: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PICreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Pi */
  get_pi_api_v1_pis__pi_id__get: {
    parameters: {
      path: {
        pi_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Pi */
  delete_pi_api_v1_pis__pi_id__delete: {
    parameters: {
      path: {
        pi_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Pi */
  update_pi_api_v1_pis__pi_id__patch: {
    parameters: {
      path: {
        pi_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PIUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PIResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Swimlines */
  list_swimlines_api_v1_pis__pi_id__swimlines_get: {
    parameters: {
      path: {
        pi_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SwimlineResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Swimline */
  create_swimline_api_v1_pis__pi_id__swimlines_post: {
    parameters: {
      path: {
        pi_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SwimlineCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SwimlineResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Swimline */
  get_swimline_api_v1_swimlines__swimline_id__get: {
    parameters: {
      path: {
        swimline_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SwimlineResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Swimline */
  delete_swimline_api_v1_swimlines__swimline_id__delete: {
    parameters: {
      path: {
        swimline_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Swimline */
  update_swimline_api_v1_swimlines__swimline_id__patch: {
    parameters: {
      path: {
        swimline_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SwimlineUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SwimlineResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Groups */
  list_groups_api_v1_swimlines__swimline_id__groups_get: {
    parameters: {
      path: {
        swimline_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GroupResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Group */
  create_group_api_v1_swimlines__swimline_id__groups_post: {
    parameters: {
      path: {
        swimline_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GroupCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["GroupResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Group */
  get_group_api_v1_groups__group_id__get: {
    parameters: {
      path: {
        group_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GroupResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Group */
  delete_group_api_v1_groups__group_id__delete: {
    parameters: {
      path: {
        group_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Group */
  update_group_api_v1_groups__group_id__patch: {
    parameters: {
      path: {
        group_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GroupUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GroupResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Sprints */
  list_sprints_api_v1_pis__pi_id__sprints_get: {
    parameters: {
      path: {
        pi_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SprintResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Sprint */
  create_sprint_api_v1_pis__pi_id__sprints_post: {
    parameters: {
      path: {
        pi_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SprintCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SprintResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Sprint */
  update_sprint_api_v1_sprints__sprint_id__patch: {
    parameters: {
      path: {
        sprint_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SprintUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SprintResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Edit Lock */
  get_edit_lock_api_v1_projects__project_id__edit_lock_get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EditLockResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Acquire Edit Lock */
  acquire_edit_lock_api_v1_projects__project_id__edit_lock_acquire_post: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EditLockResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Release Edit Lock */
  release_edit_lock_api_v1_projects__project_id__edit_lock_release_post: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Keepalive Edit Lock */
  keepalive_edit_lock_api_v1_projects__project_id__edit_lock_keepalive_post: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EditLockResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Project Events */
  project_events_api_v1_projects__project_id__events_get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
