"""initial schema

Revision ID: 175cae587c58
Revises: 
Create Date: 2026-05-03 21:12:48.917573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175cae587c58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('system_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_name', ['name'], unique=False)

    op.create_table('sessions',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('remember_me', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('username', 'session_id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('idx_sessions_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_sessions_username', ['username'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('edit_lock',
    sa.Column('system_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('locked_by_username', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.system_id'], ),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('project_id')
    )
    with op.batch_alter_table('edit_lock', schema=None) as batch_op:
        batch_op.create_index('idx_edit_lock_project', ['project_id'], unique=False)

    op.create_table('pis',
    sa.Column('system_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.system_id'], ),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    with op.batch_alter_table('pis', schema=None) as batch_op:
        batch_op.create_index('idx_pis_project', ['project_id'], unique=False)

    op.create_table('sprints',
    sa.Column('system_id', sa.Text(), nullable=False),
    sa.Column('pi_id', sa.Text(), nullable=False),
    sa.Column('sprint_index', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pi_id'], ['pis.system_id'], ),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('pi_id', 'sprint_index')
    )
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.create_index('idx_sprints_pi', ['pi_id'], unique=False)

    op.create_table('swimlines',
    sa.Column('system_id', sa.Text(), nullable=False),
    sa.Column('pi_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pi_id'], ['pis.system_id'], ),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('pi_id', 'name')
    )
    with op.batch_alter_table('swimlines', schema=None) as batch_op:
        batch_op.create_index('idx_swimlines_pi', ['pi_id'], unique=False)

    op.create_table('features',
    sa.Column('system_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effort', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('pi_id', sa.Text(), nullable=True),
    sa.Column('swimlane_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pi_id'], ['pis.system_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.system_id'], ),
    sa.ForeignKeyConstraint(['swimlane_id'], ['swimlines.system_id'], ),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('project_id', 'user_id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index('idx_features_pi', ['pi_id'], unique=False)
        batch_op.create_index('idx_features_project', ['project_id'], unique=False)
        batch_op.create_index('idx_features_swimlane', ['swimlane_id'], unique=False)
        batch_op.create_index('idx_features_user_id', ['project_id', 'user_id'], unique=False)

    op.create_table('groups',
    sa.Column('system_id', sa.Text(), nullable=False),
    sa.Column('swimline_id', sa.Text(), nullable=False),
    sa.Column('feature_system_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sprint_index', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_system_id'], ['features.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['swimline_id'], ['swimlines.system_id'], ),
    sa.PrimaryKeyConstraint('system_id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index('idx_groups_feature', ['feature_system_id'], unique=False)
        batch_op.create_index('idx_groups_swimline', ['swimline_id'], unique=False)

    op.create_table('pbis',
    sa.Column('system_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_feature_system_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effort', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('pi_id', sa.Text(), nullable=True),
    sa.Column('swimlane_id', sa.Text(), nullable=True),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.system_id'], ),
    sa.ForeignKeyConstraint(['parent_feature_system_id'], ['features.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pi_id'], ['pis.system_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.system_id'], ),
    sa.ForeignKeyConstraint(['swimlane_id'], ['swimlines.system_id'], ),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('project_id', 'user_id')
    )
    with op.batch_alter_table('pbis', schema=None) as batch_op:
        batch_op.create_index('idx_pbis_group', ['group_id'], unique=False)
        batch_op.create_index('idx_pbis_parent', ['parent_feature_system_id'], unique=False)
        batch_op.create_index('idx_pbis_pi', ['pi_id'], unique=False)
        batch_op.create_index('idx_pbis_project', ['project_id'], unique=False)
        batch_op.create_index('idx_pbis_user_id', ['project_id', 'user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pbis', schema=None) as batch_op:
        batch_op.drop_index('idx_pbis_user_id')
        batch_op.drop_index('idx_pbis_project')
        batch_op.drop_index('idx_pbis_pi')
        batch_op.drop_index('idx_pbis_parent')
        batch_op.drop_index('idx_pbis_group')

    op.drop_table('pbis')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index('idx_groups_swimline')
        batch_op.drop_index('idx_groups_feature')

    op.drop_table('groups')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index('idx_features_user_id')
        batch_op.drop_index('idx_features_swimlane')
        batch_op.drop_index('idx_features_project')
        batch_op.drop_index('idx_features_pi')

    op.drop_table('features')
    with op.batch_alter_table('swimlines', schema=None) as batch_op:
        batch_op.drop_index('idx_swimlines_pi')

    op.drop_table('swimlines')
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.drop_index('idx_sprints_pi')

    op.drop_table('sprints')
    with op.batch_alter_table('pis', schema=None) as batch_op:
        batch_op.drop_index('idx_pis_project')

    op.drop_table('pis')
    with op.batch_alter_table('edit_lock', schema=None) as batch_op:
        batch_op.drop_index('idx_edit_lock_project')

    op.drop_table('edit_lock')
    op.drop_table('users')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_sessions_username')
        batch_op.drop_index('idx_sessions_expires')

    op.drop_table('sessions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_name')

    op.drop_table('projects')
    # ### end Alembic commands ###
