"""add effort_unit to projects

Revision ID: 54393cb264c1
Revises: d4e8f2a1b3c9
Create Date: 2026-05-17 16:09:23.301431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54393cb264c1'
down_revision: Union[str, Sequence[str], None] = 'd4e8f2a1b3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effort_unit', sa.Text(), server_default='pts', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('effort_unit')

    # ### end Alembic commands ###
