"""add unique constraint groups swimline name

Revision ID: b8146781c586
Revises: 175cae587c58
Create Date: 2026-05-04 19:07:28.761261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8146781c586'
down_revision: Union[str, Sequence[str], None] = '175cae587c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_groups_swimline_name', ['swimline_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint('uq_groups_swimline_name', type_='unique')

    # ### end Alembic commands ###
